# -*- coding: utf-8 -*-
"""Untitled40.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xRMMnEGT-vU5Sq8W3Z9a5EWNgpUge5pC
"""

# --- 0) 설치 (처음 1회) ---
!pip -q install catboost

import numpy as np
import pandas as pd
from google.colab import files
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler, FunctionTransformer
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.inspection import permutation_importance
import matplotlib.pyplot as plt
from catboost import CatBoostClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score, average_precision_score, precision_recall_curve
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

uploaded = files.upload()
train = pd.read_csv("train.csv", sep=";")
test  = pd.read_csv("test.csv",  sep=";")
print(train.shape, test.shape)
print(train.columns)
train.head()

"""# EDA

1 - age (numeric)
2 - job : type of job (categorical: "admin.","unknown","unemployed","management","housemaid","entrepreneur","student",
"blue-collar","self-employed","retired","technician","services")
3 - marital : marital status (categorical: "married","divorced","single"; note: "divorced" means divorced or widowed)
4 - education (categorical: "unknown","secondary","primary","tertiary")
5 - default: has credit in default? (binary: "yes","no")
6 - balance: average yearly balance, in euros (numeric)
7 - housing: has housing loan? (binary: "yes","no")
8 - loan: has personal loan? (binary: "yes","no")
related with the last contact of the current campaign:
9 - contact: contact communication type (categorical: "unknown","telephone","cellular")
10 - day: last contact day of the month (numeric)
11 - month: last contact month of year (categorical: "jan", "feb", "mar", …, "nov", "dec")
12 - duration: last contact duration, in seconds (numeric)
other attributes:
13 - campaign: number of contacts performed during this campaign and for this client (numeric, includes last contact)
14 - pdays: number of days that passed by after the client was last contacted from a previous campaign (numeric, -1 means client was not previously contacted)
15 - previous: number of contacts performed before this campaign and for this client (numeric)
16 - poutcome: outcome of the previous marketing campaign (categorical: "unknown","other","failure","success")
"""

# Train data EDA
print("train:", train.shape)
print("test :", test.shape)

display(train.head())

# columns data types
print("\n[dtypes]")
display(train.dtypes)

# missing columns
print("\n[missing]")
display(train.isna().sum().sort_values(ascending=False).head(20))

#Test data Check

# train and test columns check
print("\n[columns]")
display(set(train.columns) - set(test.columns), set(test.columns) - set(train.columns))

#test data missing and types
print("\n[missing]")
display(test.isna().sum().sort_values(ascending=False).head(10))

print("\n[types]")
display(test.dtypes)

"""# 타겟 분포(불균형 확인) (필수)

##### 가입(yes)이 적으면 accuracy 말고 ROC-AUC / PR-AUC로 평가.
"""

display(train["y"].value_counts())
display(train["y"].value_counts(normalize=True))

"""# 범주형: unknown 비중 + 카테고리 수 (필수)"""

cat_cols = ["job","marital","education","default","housing","loan","contact","month","poutcome"]

for c in cat_cols:
    print(f"\n== {c} ==")
    vc = train[c].value_counts(dropna=False)
    print("n_unique:", train[c].nunique(), " top:\n", vc.head(12))
    print("unknown ratio:", (train[c].astype(str)=="unknown").mean())

"""# 수치형: 분포/이상치/특수값 체크 (필수)"""

num_cols = ["age","balance","day","duration","campaign","pdays","previous"]
display(train[num_cols].describe().T)

# pdays 특수값(-1) 비중
print("pdays == -1 ratio:", (train["pdays"]==-1).mean())

"""# Visualization"""

# 타겟
target_col = "y"

# 연속형(숫자형)
num_cols = ["age","balance","day","duration","campaign","pdays","previous"]

# 범주형
cat_cols = ["job","marital","education","default","housing","loan","contact","month","poutcome"]

"""# Y distribution"""

vc = train[target_col].value_counts()

plt.figure()
plt.bar(vc.index.astype(str), vc.values)
plt.title("Target distribution (y)")
plt.xlabel("y")
plt.ylabel("count")
plt.show()

"""# Num distribution"""

for c in num_cols:
    if c not in train.columns:
        continue

    plt.figure()
    train[c].hist(bins=40)
    plt.title(f"Histogram: {c}")
    plt.xlabel(c)
    plt.ylabel("count")
    plt.show()

"""# cat distribution"""

TOP_N = 12

for c in cat_cols:
    if c not in train.columns:
        continue

    vc = train[c].value_counts(dropna=False).head(TOP_N)

    plt.figure()
    plt.bar(vc.index.astype(str), vc.values)
    plt.title(f"Top {TOP_N} categories: {c}")
    plt.xlabel(c)
    plt.ylabel("count")
    plt.xticks(rotation=45, ha="right")
    plt.show()

"""# 상관관계 (계좌, 캠페인, 이전켐페인에서 고객한테 연락한수)"""

num_cols = ["balance","campaign","previous"]  # 너가 최종 남긴 숫자형만
corr = train[num_cols].corr()

plt.figure(figsize=(4,3))
plt.imshow(corr)
plt.xticks(range(len(num_cols)), num_cols, rotation=45, ha="right")
plt.yticks(range(len(num_cols)), num_cols)
plt.colorbar()
plt.title("Correlation (numeric features)")
plt.show()

"""# 범주형 yes rate

"""

def plot_yes_rate(col, top_n=12):
    tmp = train.copy()
    tmp["y_bin"] = (tmp["y"]=="yes").astype(int)
    stat = tmp.groupby(col)["y_bin"].agg(rate="mean", n="size").sort_values("rate", ascending=False).head(top_n)

    plt.figure(figsize=(7,3))
    plt.bar(stat.index.astype(str), stat["rate"])
    plt.xticks(rotation=45, ha="right")
    plt.title(f"Yes rate by {col}")
    plt.ylabel("P(y=yes)")
    plt.show()

plot_yes_rate("poutcome")
plot_yes_rate("contact")
plot_yes_rate("month")

"""# Permutation Importance"""

# ========= 0) 공통 함수 =========
def signed_log1p(x):
    return np.sign(x) * np.log1p(np.abs(x))

signed_log_tf = FunctionTransformer(signed_log1p, feature_names_out="one-to-one")
log1p_tf = FunctionTransformer(np.log1p, feature_names_out="one-to-one")

def build_clf(X):
    cat_cols = X.select_dtypes(include="object").columns.tolist()

    num_log_signed = [c for c in ["balance"] if c in X.columns]
    num_log_pos = [c for c in ["campaign","previous"] if c in X.columns]

    num_other = [
        c for c in X.columns
        if (c not in cat_cols + num_log_signed + num_log_pos)
        and (pd.api.types.is_numeric_dtype(X[c]))
    ]

    preprocess = ColumnTransformer(
        transformers=[
            ("num_signedlog", Pipeline([
                ("imp", SimpleImputer(strategy="median")),
                ("log", signed_log_tf),
                ("sc", StandardScaler()),
            ]), num_log_signed),

            ("num_log", Pipeline([
                ("imp", SimpleImputer(strategy="median")),
                ("log", log1p_tf),
                ("sc", StandardScaler()),
            ]), num_log_pos),

            ("num", Pipeline([
                ("imp", SimpleImputer(strategy="median")),
                ("sc", StandardScaler()),
            ]), num_other),

            ("cat", Pipeline([
                ("imp", SimpleImputer(strategy="most_frequent")),
                ("oh", OneHotEncoder(handle_unknown="ignore")),
            ]), cat_cols),
        ],
        remainder="drop"
    )

    return Pipeline([
        ("prep", preprocess),
        ("model", LogisticRegression(max_iter=2000, class_weight="balanced"))
    ])

def eval_auc(X, y):
    X_tr, X_va, y_tr, y_va = train_test_split(
        X, y, test_size=0.2, random_state=42, stratify=y
    )
    clf = build_clf(X)
    clf.fit(X_tr, y_tr)
    proba = clf.predict_proba(X_va)[:, 1]
    auc = roc_auc_score(y_va, proba)
    return auc


# ========= 1) 데이터 준비 =========
y = train["y"].map({"yes": 1, "no": 0})

# (A) all 버전: duration만 제거 + never_contacted 생성 + pdays는 NA 처리(선택)
X_all = train.drop(columns=["y","duration"], errors="ignore").copy()
X_all["never_contacted"] = (X_all["pdays"] == -1).astype(int)
X_all.loc[X_all["pdays"] == -1, "pdays"] = pd.NA  # pdays 숫자 자체는 의미 약해서 NA로

# (B) drop 버전: age/default/day/pdays 제거 + never_contacted는 원본 train 기준으로 생성
drop_cols = ["age","default","day","pdays"]
X_drop = X_all.drop(columns=[c for c in drop_cols if c in X_all.columns], errors="ignore").copy()


# ========= 2) AUC 비교 =========
auc_all = eval_auc(X_all, y)
auc_drop = eval_auc(X_drop, y)

print("AUC(all): ", auc_all)
print("AUC(drop):", auc_drop, " dropped=", [c for c in drop_cols if c in X_all.columns])
print("diff:", auc_drop - auc_all)


# ========= 3) (선택) 최종셋(X_drop)으로 permutation importance + plot =========
X_tr, X_va, y_tr, y_va = train_test_split(
    X_drop, y, test_size=0.2, random_state=42, stratify=y
)

clf_final = build_clf(X_drop)
clf_final.fit(X_tr, y_tr)

r = permutation_importance(
    clf_final, X_va, y_va,
    n_repeats=15, random_state=42, scoring="roc_auc"
)

imp = (pd.DataFrame({"feature": X_va.columns, "importance": r.importances_mean})
       .sort_values("importance", ascending=False))

display(imp)

top = imp.head(15)[::-1]
plt.figure(figsize=(8,5))
plt.barh(top["feature"], top["importance"])
plt.title("Permutation Importance (final X_drop, log+scale)")
plt.xlabel("Importance (ROC-AUC drop)")
plt.ylabel("Feature")
plt.show()

"""# Model and prediction"""

# --- 1) 데이터 준비 (너가 확정한 최종셋) ---
y = train["y"].map({"yes": 1, "no": 0})

drop_cols = ["y","duration","age","default","day","pdays"]  # 최종 드랍
X = train.drop(columns=[c for c in drop_cols if c in train.columns]).copy()

# never_contacted는 pdays 원본으로 생성 (train에서 가져옴)
X["never_contacted"] = (train["pdays"] == -1).astype(int)

# CatBoost가 범주형을 잘 읽도록 object/string 유지
cat_cols = X.select_dtypes(include="object").columns.tolist()
for c in cat_cols:
    X[c] = X[c].astype(str).fillna("NA")

# --- 2) Split (8:2) ---
X_tr, X_va, y_tr, y_va = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

cat_idx = [X.columns.get_loc(c) for c in cat_cols]

# --- 3) CatBoost 학습 (early stopping 포함) ---
model = CatBoostClassifier(
    iterations=3000,
    learning_rate=0.05,
    depth=6,
    loss_function="Logloss",
    eval_metric="AUC",
    random_seed=42,
    verbose=200
)

model.fit(
    X_tr, y_tr,
    cat_features=cat_idx,
    eval_set=(X_va, y_va),
    use_best_model=True,
    early_stopping_rounds=200
)

# --- 4) 평가: ROC-AUC + PR-AUC(AP) ---
proba = model.predict_proba(X_va)[:, 1]

roc = roc_auc_score(y_va, proba)
pr  = average_precision_score(y_va, proba)
base_rate = y_va.mean()  # PR-AUC의 랜덤 기준선(=양성 비율)

print("ROC-AUC:", roc)
print("PR-AUC (AP):", pr)
print("Positive rate (baseline for PR-AUC):", base_rate)
print("Lift over baseline (AP / base_rate):", pr / base_rate if base_rate > 0 else np.nan)

# ===== 1) train 전체 준비 =====
y_train_full = train["y"].map({"yes": 1, "no": 0})

drop_cols = ["y","duration","age","default","day","pdays"]
X_train_full = train.drop(columns=[c for c in drop_cols if c in train.columns]).copy()
X_train_full["never_contacted"] = (train["pdays"] == -1).astype(int)

cat_cols = X_train_full.select_dtypes(include="object").columns.tolist()
for c in cat_cols:
    X_train_full[c] = X_train_full[c].astype(str).fillna("NA")
cat_idx = [X_train_full.columns.get_loc(c) for c in cat_cols]

train_pool_full = Pool(X_train_full, y_train_full, cat_features=cat_idx)

# ===== 2) 100% train 모델 학습 (bestIteration 기반) =====
final_model_full = CatBoostClassifier(
    iterations=830, learning_rate=0.05, depth=6,
    loss_function="Logloss", eval_metric="AUC",
    random_seed=42, verbose=200
)
final_model_full.fit(train_pool_full)

# ===== 3) test 평가 =====
y_test = test["y"].map({"yes": 1, "no": 0})

X_test = test.drop(columns=[c for c in drop_cols if c in test.columns], errors="ignore").copy()
X_test["never_contacted"] = (test["pdays"] == -1).astype(int) if "pdays" in test.columns else 0
X_test = X_test.reindex(columns=X_train_full.columns)

for c in cat_cols:
    X_test[c] = X_test[c].astype(str).fillna("NA")

test_pool = Pool(X_test, cat_features=cat_idx)
proba_test = final_model_full.predict_proba(test_pool)[:, 1]

print("ROC-AUC:", roc_auc_score(y_test, proba_test))
print("PR-AUC:", average_precision_score(y_test, proba_test))

pred_05 = (proba_test >= 0.5).astype(int)
print("Accuracy:", accuracy_score(y_test, pred_05))
print("Confusion:\n", confusion_matrix(y_test, pred_05))
print(classification_report(y_test, pred_05, digits=4))

def top_k_metrics(proba, y_true, pct):
    n = len(proba)
    k = int(np.ceil(n * pct))

    idx = np.argsort(-proba)[:k]

    precision = y_true.iloc[idx].mean()
    recall = y_true.iloc[idx].sum() / y_true.sum()

    print(f"\nTop {int(pct*100)}%")
    print("k =", k)
    print("precision:", round(precision, 4))
    print("recall:", round(recall, 4))

# 실행
top_k_metrics(proba_test, y_test, 0.05)
top_k_metrics(proba_test, y_test, 0.10)
top_k_metrics(proba_test, y_test, 0.20)

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

def top_k_summary(proba, y_true, pct_list=(0.05, 0.10, 0.20)):
    y_true = pd.Series(y_true).reset_index(drop=True)
    proba = np.asarray(proba)

    n = len(proba)
    total_pos = int(y_true.sum())

    rows = []
    for pct in pct_list:
        k = int(np.ceil(n * pct))
        idx = np.argsort(-proba)[:k]  # 상위 k

        tp = int(y_true.iloc[idx].sum())
        fp = int(k - tp)
        precision = tp / k if k > 0 else np.nan
        recall = tp / total_pos if total_pos > 0 else np.nan

        rows.append({
            "Top_%": int(pct * 100),
            "k (Calls)": k,
            "TP (True Yes)": tp,
            "FP (False Yes)": fp,
            "Precision": precision,
            "Recall": recall
        })

    return pd.DataFrame(rows)

pct_list = [0.05, 0.10, 0.20]
topk_df = top_k_summary(proba_test, y_test, pct_list)
topk_df

# Stacked bar: TP + FP = Calls
x = topk_df["Top_%"].astype(str) + "%"
tp = topk_df["TP (True Yes)"].values
fp = topk_df["FP (False Yes)"].values

plt.figure(figsize=(8,5))
plt.bar(x, tp, label="TP (Actual Yes among targeted)")
plt.bar(x, fp, bottom=tp, label="FP (Actual No among targeted)")
plt.title("Top-k Targeting: TP vs FP (Counts)")
plt.xlabel("Targeted Top %")
plt.ylabel("Number of Customers")
plt.grid(True, axis="y")
plt.legend()
plt.show()

prec, rec, thr = precision_recall_curve(y_test, proba_test)

f1 = 2 * prec * rec / (prec + rec + 1e-12)
best_idx = np.argmax(f1)

best_thr = thr[best_idx]
print("Best threshold (F1 max):", best_thr)
print("Precision:", prec[best_idx])
print("Recall:", rec[best_idx])
print("F1:", f1[best_idx])

import numpy as np
import pandas as pd

from catboost import CatBoostClassifier, Pool
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import roc_auc_score, average_precision_score

# -----------------------
# 1) 데이터 준비 (너가 확정한 피처셋)
# -----------------------
drop_cols = ["y","duration","age","default","day","pdays"]

y = train["y"].map({"yes": 1, "no": 0})

X = train.drop(columns=[c for c in drop_cols if c in train.columns], errors="ignore").copy()
X["never_contacted"] = (train["pdays"] == -1).astype(int)

cat_cols = X.select_dtypes(include="object").columns.tolist()
for c in cat_cols:
    X[c] = X[c].astype(str).fillna("NA")
cat_idx = [X.columns.get_loc(c) for c in cat_cols]

# -----------------------
# 2) OOF 예측확률 생성
# -----------------------
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
oof_proba = np.zeros(len(X))

for fold, (tr_idx, va_idx) in enumerate(skf.split(X, y), 1):
    X_tr, y_tr = X.iloc[tr_idx], y.iloc[tr_idx]
    X_va, y_va = X.iloc[va_idx], y.iloc[va_idx]

    tr_pool = Pool(X_tr, y_tr, cat_features=cat_idx)
    va_pool = Pool(X_va, cat_features=cat_idx)

    m = CatBoostClassifier(
        iterations=830,
        learning_rate=0.05,
        depth=6,
        loss_function="Logloss",
        eval_metric="AUC",
        random_seed=42,
        verbose=0
    )
    m.fit(tr_pool)

    oof_proba[va_idx] = m.predict_proba(va_pool)[:, 1]

print("OOF ROC-AUC:", roc_auc_score(y, oof_proba))
print("OOF PR-AUC :", average_precision_score(y, oof_proba))

# -----------------------
# 3) Profit 최적 threshold 찾기
# -----------------------
def best_threshold_by_profit(y_true, proba, revenue=20.0, cost=1.0):
    # threshold 후보를 확률값들로 (혹은 0~1 grid로 해도 됨)
    thresholds = np.unique(np.round(proba, 6))
    best = {"thr": None, "profit": -1e18, "tp": None, "fp": None, "precision": None, "recall": None}

    y_true = np.asarray(y_true)

    for t in thresholds:
        pred = (proba >= t).astype(int)
        tp = ((pred == 1) & (y_true == 1)).sum()
        fp = ((pred == 1) & (y_true == 0)).sum()
        fn = ((pred == 0) & (y_true == 1)).sum()

        profit = tp * revenue - (tp + fp) * cost

        precision = tp / (tp + fp + 1e-12)
        recall = tp / (tp + fn + 1e-12)

        if profit > best["profit"]:
            best = {"thr": float(t), "profit": float(profit), "tp": int(tp), "fp": int(fp),
                    "precision": float(precision), "recall": float(recall)}

    return best

best = best_threshold_by_profit(y, oof_proba, revenue=20, cost=1)
print("\n[Best threshold by PROFIT on OOF]")
print(best)

# y: (0/1) Series, oof_proba: OOF predicted probabilities (np.array)
# revenue, cost: 너가 쓴 값 그대로
revenue = 20.0
cost = 1.0

y_true = np.asarray(y)  # y는 너 OOF 만들 때 썼던 train의 y (0/1)
proba = np.asarray(oof_proba)

# threshold 후보: 0~1 grid (부드러운 커브)
thresholds = np.linspace(0, 1, 1001)

profits = []
precisions = []
recalls = []
calls = []

pos_total = (y_true == 1).sum()

for t in thresholds:
    pred = (proba >= t).astype(int)
    tp = ((pred == 1) & (y_true == 1)).sum()
    fp = ((pred == 1) & (y_true == 0)).sum()
    fn = ((pred == 0) & (y_true == 1)).sum()

    profit = tp * revenue - (tp + fp) * cost
    precision = tp / (tp + fp + 1e-12)
    recall = tp / (tp + fn + 1e-12)
    call_n = tp + fp

    profits.append(profit)
    precisions.append(precision)
    recalls.append(recall)
    calls.append(call_n)

profits = np.array(profits)
precisions = np.array(precisions)
recalls = np.array(recalls)
calls = np.array(calls)

best_idx = np.argmax(profits)
best_t = thresholds[best_idx]

print("=== Best by Profit (OOF) ===")
print("best_threshold:", best_t)
print("best_profit:", profits[best_idx])
print("precision:", precisions[best_idx])
print("recall:", recalls[best_idx])
print("calls:", calls[best_idx], " / total:", len(y_true))

# Plot
plt.figure(figsize=(9,5))
plt.plot(thresholds, profits)
plt.axvline(best_t, linestyle="--")
plt.scatter([best_t], [profits[best_idx]])
plt.title("Profit Curve (OOF) vs Threshold")
plt.xlabel("Threshold")
plt.ylabel("Expected Profit")
plt.grid(True)
plt.show()

# (선택) 같이 보고 싶으면: precision/recall 곡선
plt.figure(figsize=(9,5))
plt.plot(thresholds, precisions, label="Precision")
plt.plot(thresholds, recalls, label="Recall")
plt.axvline(best_t, linestyle="--", label=f"Best t={best_t:.3f}")
plt.title("Precision / Recall vs Threshold (OOF)")
plt.xlabel("Threshold")
plt.ylabel("Score")
plt.grid(True)
plt.legend()
plt.show()

# ===== 0) 최적 threshold =====
best_thr = 0.04822
revenue = 20
cost = 1

# ===== 1) y_test 만들기 =====
y_test = test["y"].map({"yes": 1, "no": 0})

# ===== 2) test feature 만들기 (train과 동일 규칙) =====
drop_cols = ["y","duration","age","default","day","pdays"]

X_test = test.drop(columns=[c for c in drop_cols if c in test.columns], errors="ignore").copy()

# never_contacted 생성
X_test["never_contacted"] = (test["pdays"] == -1).astype(int)

# train과 동일 컬럼 순서 맞추기
X_test = X_test.reindex(columns=X_train_full.columns)

# 범주형 동일 처리
for c in cat_cols:
    X_test[c] = X_test[c].astype(str).fillna("NA")

# ===== 3) 확률 예측 =====
test_pool = Pool(X_test, cat_features=cat_idx)
proba_test = final_model_full.predict_proba(test_pool)[:, 1]

# ===== 4) threshold 적용 =====
pred_test = (proba_test >= best_thr).astype(int)

from sklearn.metrics import roc_auc_score, average_precision_score, \
                            precision_score, recall_score, confusion_matrix, classification_report

print("ROC-AUC:", roc_auc_score(y_test, proba_test))
print("PR-AUC:", average_precision_score(y_test, proba_test))

print("\n[Threshold =", best_thr, "]")
print("Precision:", precision_score(y_test, pred_test))
print("Recall:", recall_score(y_test, pred_test))
print("Confusion Matrix:\n", confusion_matrix(y_test, pred_test))
print(classification_report(y_test, pred_test, digits=4))

tp = ((pred_test==1) & (y_test==1)).sum()
fp = ((pred_test==1) & (y_test==0)).sum()

profit_test = tp*revenue - (tp+fp)*cost

print("Calls:", tp+fp)
print("TP:", tp)
print("FP:", fp)
print("Test Profit:", profit_test)

test_result = test.copy()
test_result["pred_proba"] = proba_test
test_result["call_flag"] = pred_test

# 전화 대상만 추출
call_list = test_result[test_result["call_flag"]==1]

print("전화 대상 수:", len(call_list))

# CSV 저장 (콜센터 전달용)
call_list.to_csv("call_target_list.csv", index=False)

import numpy as np

print("Quantiles:")
print(np.quantile(proba_test, [0.01, 0.05, 0.1, 0.25, 0.5, 0.75, 0.9]))

print("\nCall rate @ 0.04822:",
      (proba_test >= 0.04822).mean())

def eval_policy(proba, y_true, revenue=20, cost=1):
    thr = cost / revenue
    pred = (proba >= thr).astype(int)
    tp = ((pred==1) & (y_true==1)).sum()
    fp = ((pred==1) & (y_true==0)).sum()
    profit = tp*revenue - (tp+fp)*cost
    call_rate = pred.mean()
    precision = tp/(tp+fp+1e-12)
    recall = tp/((y_true==1).sum()+1e-12)
    return thr, call_rate, profit, precision, recall

for c in [1,2,3,5,10]:
    thr, rate, prof, prec, rec = eval_policy(proba_test, y_test.values, revenue=20, cost=c)
    print(f"cost={c:>2} thr={thr:.3f} call_rate={rate:.3f} profit={prof:.0f} prec={prec:.3f} rec={rec:.3f}")

import numpy as np
import pandas as pd
from catboost import Pool
from sklearn.metrics import roc_auc_score, average_precision_score

# =============================
# 1️⃣ 모델 + test 확률 다시 계산
# =============================

# train 전체로 학습된 final_model_full 이 이미 있다고 가정
# 만약 없다면 다시 학습해야 함

drop_cols = ["y","duration","age","default","day","pdays"]

y_test = test["y"].map({"yes": 1, "no": 0})

X_test = test.drop(columns=[c for c in drop_cols if c in test.columns], errors="ignore").copy()
X_test["never_contacted"] = (test["pdays"] == -1).astype(int)

X_test = X_test.reindex(columns=X_train_full.columns)

for c in cat_cols:
    X_test[c] = X_test[c].astype(str).fillna("NA")

test_pool = Pool(X_test, cat_features=cat_idx)
proba_test = final_model_full.predict_proba(test_pool)[:, 1]

# =============================
# 2️⃣ 민감도 분석 테이블 생성
# =============================

revenue = 20
cost_list = [1, 2, 3, 5, 7, 10]

rows = []
y_true = y_test.values
pos_total = (y_true == 1).sum()

for cost in cost_list:
    thr = cost / revenue
    pred = (proba_test >= thr).astype(int)

    tp = ((pred==1) & (y_true==1)).sum()
    fp = ((pred==1) & (y_true==0)).sum()
    fn = ((pred==0) & (y_true==1)).sum()

    profit = tp*revenue - (tp+fp)*cost
    call_rate = pred.mean()
    precision = tp/(tp+fp+1e-12)
    recall = tp/(pos_total+1e-12)

    rows.append({
        "Cost_per_Call": cost,
        "Threshold": round(thr, 3),
        "Call_Rate(%)": round(call_rate*100, 2),
        "Calls": int(tp+fp),
        "TP": int(tp),
        "FP": int(fp),
        "Precision": round(precision, 3),
        "Recall": round(recall, 3),
        "Expected_Profit": int(profit)
    })

report_table = pd.DataFrame(rows)

report_table

from sklearn.isotonic import IsotonicRegression
from sklearn.metrics import brier_score_loss

# (1) Isotonic calibrator 학습: (oof_proba -> y)
iso = IsotonicRegression(out_of_bounds="clip")
iso.fit(oof_proba, y.values)

# (2) OOF 확률 보정
oof_proba_iso = iso.transform(oof_proba)

print("\n[Calibration check on OOF]")
print("Brier(raw):", brier_score_loss(y, oof_proba))
print("Brier(iso):", brier_score_loss(y, oof_proba_iso))

print("OOF ROC-AUC raw:", roc_auc_score(y, oof_proba))
print("OOF ROC-AUC iso:", roc_auc_score(y, oof_proba_iso))  # 거의 같아야 정상(랭킹 유지)
print("OOF PR-AUC  raw:", average_precision_score(y, oof_proba))
print("OOF PR-AUC  iso:", average_precision_score(y, oof_proba_iso))  # 거의 같아야 정상

best_raw = best_threshold_by_profit(y, oof_proba, revenue=20, cost=1)
best_iso = best_threshold_by_profit(y, oof_proba_iso, revenue=20, cost=1)

print("\n[Best threshold by PROFIT on OOF - RAW]")
print(best_raw)

print("\n[Best threshold by PROFIT on OOF - ISOTONIC]")
print(best_iso)

print("\n[Diff]")
print("thr diff:", best_iso["thr"] - best_raw["thr"])
print("profit diff:", best_iso["profit"] - best_raw["profit"])

import matplotlib.pyplot as plt

def profit_curve(y_true, proba, revenue=20.0, cost=1.0, grid=400):
    y_true = np.asarray(y_true)
    thr_list = np.linspace(0, 1, grid)
    profits = []
    calls = []
    for t in thr_list:
        pred = (proba >= t).astype(int)
        tp = ((pred==1) & (y_true==1)).sum()
        fp = ((pred==1) & (y_true==0)).sum()
        profit = tp*revenue - (tp+fp)*cost
        profits.append(profit)
        calls.append(pred.mean())
    return thr_list, np.array(profits), np.array(calls)

thr, p_raw, call_raw = profit_curve(y, oof_proba, revenue=20, cost=1)
thr, p_iso, call_iso = profit_curve(y, oof_proba_iso, revenue=20, cost=1)

plt.figure(figsize=(8,5))
plt.plot(thr, p_raw, label="Profit (raw proba)")
plt.plot(thr, p_iso, label="Profit (isotonic calibrated)")
plt.axvline(best_raw["thr"], linestyle="--", label=f"best raw thr={best_raw['thr']:.3f}")
plt.axvline(best_iso["thr"], linestyle="--", label=f"best iso thr={best_iso['thr']:.3f}")
plt.xlabel("Threshold")
plt.ylabel("Profit")
plt.title("Profit Curve on OOF (raw vs isotonic)")
plt.grid(True)
plt.legend()
plt.show()

from sklearn.metrics import roc_curve, roc_auc_score
import matplotlib.pyplot as plt

fpr, tpr, _ = roc_curve(y_test, proba_test)
roc_auc = roc_auc_score(y_test, proba_test)

plt.figure(figsize=(6,6))
plt.plot(fpr, tpr, label=f"AUC = {roc_auc:.3f}")
plt.plot([0,1],[0,1],'--')
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve")
plt.legend()
plt.grid()
plt.show()

from sklearn.metrics import precision_recall_curve, average_precision_score

precision, recall, _ = precision_recall_curve(y_test, proba_test)
ap = average_precision_score(y_test, proba_test)

plt.figure(figsize=(6,6))
plt.plot(recall, precision, label=f"AP = {ap:.3f}")
plt.xlabel("Recall")
plt.ylabel("Precision")
plt.title("Precision-Recall Curve")
plt.legend()
plt.grid()
plt.show()

thresholds = np.linspace(0,1,200)
profits = []
call_rates = []

for t in thresholds:
    pred = (proba_test >= t).astype(int)
    tp = ((pred==1)&(y_test==1)).sum()
    fp = ((pred==1)&(y_test==0)).sum()
    profit = tp*20 - (tp+fp)*1
    profits.append(profit)
    call_rates.append(pred.mean())

plt.figure(figsize=(7,5))
plt.plot(call_rates, profits)
plt.xlabel("Call Rate")
plt.ylabel("Expected Profit")
plt.title("Profit vs Call Rate")
plt.grid()
plt.show()

df_eval = pd.DataFrame({
    "proba": proba_test,
    "y": y_test
}).sort_values("proba", ascending=False)

df_eval["cum_pos"] = df_eval["y"].cumsum()
df_eval["cum_rate"] = df_eval["cum_pos"] / df_eval["y"].sum()
df_eval["percent"] = np.arange(1,len(df_eval)+1)/len(df_eval)

plt.figure(figsize=(7,5))
plt.plot(df_eval["percent"], df_eval["cum_rate"])
plt.xlabel("Proportion of Customers Contacted")
plt.ylabel("Proportion of Total Conversions Captured")
plt.title("Gain Chart")
plt.grid()
plt.show()

plt.figure(figsize=(7,5))
plt.plot(df_eval["percent"], df_eval["cum_rate"], label="Model")
plt.plot([0,1],[0,1], linestyle="--", label="Random")
plt.xlabel("Proportion of Customers Contacted")
plt.ylabel("Proportion of Total Conversions Captured")
plt.title("Gain Chart")
plt.legend()
plt.grid()
plt.show()

import numpy as np

# 확률 + 원본 데이터 합치기
df_analysis = X_test.copy()
df_analysis["proba"] = proba_test
df_analysis["y"] = y_test.values

# 상위 20% 인원수 계산
k = int(len(df_analysis) * 0.20)

# 확률 높은 순으로 정렬
df_top20 = df_analysis.sort_values("proba", ascending=False).head(k)

print("상위 20% 인원:", len(df_top20))
print("전체 가입자 중 상위 20%에서 잡은 비율:",
      df_top20["y"].sum() / df_analysis["y"].sum())

for col in ["job", "marital", "education", "housing", "loan"]:
    print("\n====", col, "====")
    print("전체 비율:")
    print(df_analysis[col].value_counts(normalize=True).round(3))

    print("\n상위 20% 비율:")
    print(df_top20[col].value_counts(normalize=True).round(3))

for col in ["balance", "campaign", "previous"]:
    print("\n====", col, "====")
    print("전체 평균:", df_analysis[col].mean())
    print("상위 20% 평균:", df_top20[col].mean())

import matplotlib.pyplot as plt

job_total = df_analysis["job"].value_counts(normalize=True)
job_top = df_top20["job"].value_counts(normalize=True)

df_compare = pd.DataFrame({
    "Total": job_total,
    "Top20%": job_top
}).fillna(0)

df_compare.plot(kind="bar", figsize=(10,5))
plt.title("Job Distribution: Total vs Top 20%")
plt.ylabel("Proportion")
plt.show()

